[package]
name = "kiy4ku/ragdoll-service"
description = "Easy-to-use and lightweight ragdoll service for Roblox Games"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
component = "sleitnick/component@2.4.8"
trove = "sleitnick/trove@1.4.0"
warp = "imezx/warp@1.0.12"
promise = "evaera/promise@4.0.0"