name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup tools
      - name: Run aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          version: v0.3.0

      # Run linter
      - name: Update standard library
        run: selene update-roblox-std

      - name: Run Selene
        run: selene --allow-warnings ./src

      - name: Validate Stylua
        run: stylua -c ./src